plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'idea'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        clientWithMods {
            client() // same setup as normal client
            ideName = "runClient with Mods (${project.path})"
            gameDirectory = project.file('run_with_mods')
        }
        data {
            clientData()

            // example of overriding the workingDirectory set in configureEach above, uncomment if you want to use it
            // gameDirectory = project.file('run-data')

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('../common/src/generated/resources/').getAbsolutePath(), '--existing', file('../common/src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
        serverWithMods {
            server()
            ideName = "runServer with Mods (${project.path})"
            gameDirectory = project.file('run_with_mods')
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDirs (
    '../common/src/generated/resources',
    'src/generated/resources'
)

repositories {
    maven {
        url "https://nexus.resourcefulbees.com/repository/telepathicgrunt/"
    }
    maven {
        url "https://maven.twelveiterations.com/repository/maven-public/"
        content {
            includeGroup "net.blay09.mods"
        }
    }
}

dependencies {
    compileOnly "com.telepathicgrunt:RepurposedStructures:7.6.0+1.21.11-neoforge"

//    compileOnly "net.blay09.mods:balm-neoforge:21.11.2"
    compileOnly ('net.blay09.mods:waystones-neoforge:21.11.4') {
        capabilities {
            // Select the MC-specific capability that the published variants provide
            requireCapability "net.blay09.mods:waystones-neoforge-1.21.11:21.11.4"
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}